export const personalInfo = {
  name: "Rohit Shrestha",
  title: "Full Stack Developer",
  tagline: "Building digital experiences that matter",
  email: "rohitshrestha533@gmail.com",
  phone: "+977 9800000000",
  location: "Pokhara, Nepal",
  github: "https://github.com/RohitShrestha533",
  linkedin: "https://www.linkedin.com/in/rohitshrestha533",
  twitter: "https://twitter.com/rohitshrestha533",
  resume: "#",
  bio: "I'm a passionate Full Stack Developer with a deep love for crafting elegant, performant web applications. From pixel-perfect UIs to scalable backend architectures, I bring ideas to life with clean code and thoughtful design. Currently exploring the intersection of web development and data science.",
  stats: [
    { label: "Projects Completed", value: "20+" },
    { label: "Technologies", value: "15+" },
    { label: "Years Experience", value: "3+" },
    { label: "GitHub Stars", value: "50+" },
  ]
}

export const skills = {
  frontend: [
    { name: "React.js", level: 90, icon: "⚛️" },
    { name: "Next.js", level: 82, icon: "▲" },
    { name: "TypeScript", level: 78, icon: "🔷" },
    { name: "Tailwind CSS", level: 92, icon: "🎨" },
    { name: "Framer Motion", level: 75, icon: "🎭" },
    { name: "HTML/CSS", level: 95, icon: "🌐" },
  ],
  backend: [
    { name: "Node.js", level: 85, icon: "🟢" },
    { name: "Express.js", level: 83, icon: "🚀" },
    { name: "Python", level: 80, icon: "🐍" },
    { name: "FastAPI", level: 72, icon: "⚡" },
    { name: "REST APIs", level: 88, icon: "🔗" },
    { name: "GraphQL", level: 65, icon: "◆" },
  ],
  database: [
    { name: "MongoDB", level: 85, icon: "🍃" },
    { name: "PostgreSQL", level: 78, icon: "🐘" },
    { name: "MySQL", level: 75, icon: "🗄️" },
    { name: "Redis", level: 65, icon: "🔴" },
    { name: "Firebase", level: 80, icon: "🔥" },
  ],
  tools: [
    { name: "Git & GitHub", level: 90, icon: "🐙" },
    { name: "Docker", level: 70, icon: "🐳" },
    { name: "AWS", level: 65, icon: "☁️" },
    { name: "Vercel", level: 88, icon: "▲" },
    { name: "Linux", level: 75, icon: "🐧" },
    { name: "VS Code", level: 95, icon: "💻" },
  ]
}

export const projects = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description: "A full-stack e-commerce platform with real-time inventory management, payment integration, and admin dashboard. Features include cart management, user authentication, and order tracking.",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=400&fit=crop",
    tech: ["React", "Node.js", "MongoDB", "Stripe", "Redis"],
    github: "https://github.com/RohitShrestha533",
    live: "#",
    category: "fullstack",
    featured: true,
  },
  {
    id: 2,
    title: "Task Management App",
    description: "A collaborative project management tool with drag-and-drop boards, real-time updates via WebSockets, team collaboration features, and detailed analytics.",
    image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=600&h=400&fit=crop",
    tech: ["React", "Express", "Socket.io", "PostgreSQL"],
    github: "https://github.com/RohitShrestha533",
    live: "#",
    category: "fullstack",
    featured: true,
  },
  {
    id: 3,
    title: "AI Data Dashboard",
    description: "Interactive analytics dashboard with ML-powered insights, data visualization using D3.js, automated reporting, and predictive analytics for business intelligence.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop",
    tech: ["Python", "FastAPI", "React", "D3.js", "TensorFlow"],
    github: "https://github.com/RohitShrestha533",
    live: "#",
    category: "data",
    featured: true,
  },
  {
    id: 4,
    title: "Social Media API",
    description: "RESTful API for a social platform with JWT auth, file uploads, real-time notifications, rate limiting, caching, and comprehensive Swagger documentation.",
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&h=400&fit=crop",
    tech: ["Node.js", "Express", "MongoDB", "JWT", "AWS S3"],
    github: "https://github.com/RohitShrestha533",
    live: "#",
    category: "backend",
    featured: false,
  },
  {
    id: 5,
    title: "Portfolio Website v1",
    description: "A minimalist personal portfolio built with Next.js and Framer Motion featuring smooth animations, dark mode, and a blog section with MDX support.",
    image: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=600&h=400&fit=crop",
    tech: ["Next.js", "Tailwind CSS", "Framer Motion", "MDX"],
    github: "https://github.com/RohitShrestha533",
    live: "#",
    category: "frontend",
    featured: false,
  },
  {
    id: 6,
    title: "Weather Forecast App",
    description: "A beautiful weather application with location detection, 7-day forecasts, weather maps, severe weather alerts, and historical data comparison.",
    image: "https://images.unsplash.com/photo-1504608524841-42f1e89f0855?w=600&h=400&fit=crop",
    tech: ["React", "OpenWeather API", "Chart.js", "Geolocation"],
    github: "https://github.com/RohitShrestha533",
    live: "#",
    category: "frontend",
    featured: false,
  },
]

export const experience = [
  {
    id: 1,
    role: "Full Stack Developer Intern",
    company: "Tech Startup Nepal",
    location: "Kathmandu, Nepal",
    duration: "Jun 2023 – Dec 2023",
    type: "Internship",
    description: [
      "Built and maintained REST APIs using Node.js and Express serving 10K+ daily requests",
      "Developed responsive React components improving UI performance by 40%",
      "Collaborated with a team of 5 developers using Agile/Scrum methodology",
      "Integrated third-party payment gateways (eSewa, Khalti) for local transactions",
    ],
    tech: ["React", "Node.js", "MongoDB", "Express"],
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: 2,
    role: "Freelance Web Developer",
    company: "Self-Employed",
    location: "Remote",
    duration: "Jan 2023 – Present",
    type: "Freelance",
    description: [
      "Delivered 10+ client projects ranging from landing pages to full-stack applications",
      "Specialized in React.js frontends with Node.js backends and MongoDB databases",
      "Maintained a 5-star rating with 100% client satisfaction on delivered projects",
      "Handled complete project lifecycle from requirement gathering to deployment",
    ],
    tech: ["React", "Next.js", "Tailwind", "Firebase"],
    color: "from-purple-500 to-pink-500",
  },
  {
    id: 3,
    role: "Open Source Contributor",
    company: "GitHub Community",
    location: "Remote",
    duration: "2022 – Present",
    type: "Volunteer",
    description: [
      "Contributed bug fixes and features to multiple open-source React projects",
      "Created and maintained personal npm packages with 100+ weekly downloads",
      "Active in developer communities, mentoring junior developers",
      "Participated in Hacktoberfest with accepted pull requests",
    ],
    tech: ["JavaScript", "TypeScript", "React", "Python"],
    color: "from-green-500 to-emerald-500",
  },
]

export const education = [
  {
    degree: "Bachelor of Computer Science & IT",
    school: "Tribhuvan University",
    location: "Pokhara, Nepal",
    year: "2020 – 2024",
    grade: "First Division",
    description: "Specialized in software engineering, data structures, algorithms, and database management.",
  },
  {
    degree: "Higher Secondary (Science)",
    school: "Premier Higher Secondary School",
    location: "Pokhara, Nepal",
    year: "2018 – 2020",
    grade: "GPA: 3.6",
    description: "Focused on Mathematics, Physics, and Computer Science fundamentals.",
  }
]

export const achievements = [
  {
    title: "Meta Front-End Developer Certificate",
    issuer: "Coursera / Meta",
    date: "2023",
    icon: "🏆",
    link: "#",
    category: "certification",
  },
  {
    title: "MongoDB Developer Certification",
    issuer: "MongoDB University",
    date: "2023",
    icon: "🍃",
    link: "#",
    category: "certification",
  },
  {
    title: "AWS Cloud Practitioner",
    issuer: "Amazon Web Services",
    date: "2024",
    icon: "☁️",
    link: "#",
    category: "certification",
  },
  {
    title: "Hackathon Winner – HackKU 2023",
    issuer: "Kathmandu University",
    date: "2023",
    icon: "🥇",
    link: "#",
    category: "award",
  },
  {
    title: "Top Contributor – Hacktoberfest",
    issuer: "DigitalOcean",
    date: "2022 & 2023",
    icon: "🎃",
    link: "#",
    category: "award",
  },
  {
    title: "Google Data Analytics Certificate",
    issuer: "Google / Coursera",
    date: "2024",
    icon: "📊",
    link: "#",
    category: "certification",
  },
]

export const services = [
  {
    title: "Frontend Development",
    description: "Crafting pixel-perfect, responsive UIs with React, Next.js, and modern CSS. Focus on performance, accessibility, and delightful user experiences.",
    icon: "🎨",
    features: ["React / Next.js", "Responsive Design", "Animations & UX", "Performance Optimization"],
    color: "from-blue-500 to-cyan-400",
  },
  {
    title: "Backend Development",
    description: "Building robust, scalable server-side solutions with Node.js, Python, and RESTful/GraphQL APIs with proper authentication and security.",
    icon: "⚙️",
    features: ["Node.js / Express", "REST & GraphQL APIs", "Authentication & Security", "Microservices"],
    color: "from-purple-500 to-violet-400",
  },
  {
    title: "Database Design",
    description: "Designing efficient database schemas, optimizing queries, and implementing both SQL and NoSQL solutions for scalable data management.",
    icon: "🗄️",
    features: ["MongoDB & PostgreSQL", "Schema Design", "Query Optimization", "Data Modeling"],
    color: "from-green-500 to-emerald-400",
  },
  {
    title: "Cloud & Deployment",
    description: "Deploying and managing applications on AWS, Vercel, and other cloud platforms with CI/CD pipelines, containerization, and monitoring.",
    icon: "☁️",
    features: ["AWS / Vercel", "Docker & CI/CD", "Performance Monitoring", "SSL & Security"],
    color: "from-orange-500 to-amber-400",
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    role: "Product Manager",
    company: "TechCorp Nepal",
    avatar: "PS",
    text: "Rohit delivered our e-commerce platform ahead of schedule with exceptional quality. His attention to detail and proactive communication made the project a huge success. Highly recommend!",
    rating: 5,
    color: "from-pink-500 to-rose-400",
  },
  {
    id: 2,
    name: "Alex Chen",
    role: "CTO",
    company: "StartupHub",
    avatar: "AC",
    text: "Working with Rohit was a pleasure. He understood our complex requirements quickly and implemented elegant solutions. The codebase is clean, well-documented, and maintainable.",
    rating: 5,
    color: "from-blue-500 to-indigo-400",
  },
  {
    id: 3,
    name: "Sarah Johnson",
    role: "Frontend Lead",
    company: "Digital Agency",
    avatar: "SJ",
    text: "Rohit's React skills are top-notch. He built our design system from scratch, creating reusable components that our entire team now relies on. Great communicator and team player.",
    rating: 5,
    color: "from-green-500 to-teal-400",
  },
]
